name: mole_amp
channels:
  - pytorch
  - nvidia
  - rmg
  - conda-forge
  - rdkit
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - rdkit=2022.3.3
  - pip
  - pip:
    - xgboost==1.6.2
    - pandas==2.0.3
    - PyYAML==6.0.1
    - torch_geometric==2.5.0
    - openpyxl
